version: "3.7"

services:
  app:
    build:
      context: .
      target: builder
    command: run dev
    environment:
      - NODE_ENV=development
    env_file: .env
    entrypoint: npm
    ports:
      - ${PORT}:${PORT}
      - 5858:5858
    depends_on:
      - mysql
    volumes:
      - ./:/code
      - /code/node_modules

  mysql:
    image: hsheth2/mysql-low-memory:5.7
    env_file: .env
    ports:
      - 3306:3306
